#!/usr/bin/perl -w

use File::Basename;

my $homeDir = $ENV{'HOME'};
$homeDir .= '/' unless ($homeDir =~ /\/$/);
my $mountDir;
if (-d $homeDir.'mnt') {
  $mountDir = $homeDir.'mnt/';
} elsif (-d $homeDir.'mount') {
  $mountDir = $homeDir.'mount/';
} elsif (-d $homeDir.'media') {
  $mountDir = $homeDir.'media/';
} else {
  $mountDir = $homeDir;
}

my $paths = $ENV{NAUTILUS_SCRIPT_SELECTED_FILE_PATHS};
if ((!$paths) || ($paths eq "")) {
  $paths = $ENV{NEMO_SCRIPT_SELECTED_FILE_PATHS};
}

my @files = split("\n", $paths);
foreach my $isoFile (@files) {
  if (-f $isoFile) {
    my($filename, $directories, $suffix) = fileparse($isoFile);
    my $mountSubDir = $filename;
    $mountSubDir =~ s/[^a-zA-Z0-9_]/_/g;
    $mountSubDir = $mountDir.$mountSubDir;
    system('fuseiso', '-p', $isoFile, $mountSubDir);
  }
}

