#!/usr/bin/perl -w

use strict;

my $paths = $ENV{NAUTILUS_SCRIPT_SELECTED_FILE_PATHS};
if ((!$paths) || ($paths eq "")) {
  $paths = $ENV{NEMO_SCRIPT_SELECTED_FILE_PATHS};
}

my @files = split("\n", $paths);


foreach my $file (@files)
{
  if ( -e $file )
  {
    my $txtName = $file.".txt";

    `pdftotext '$file' '$txtName'`;

    if ( -e $txtName) {
      `zenity --info --text="Converted $file to $txtName"`;
    } else {
      `zenity --info --text="Failed to convert $file to $txtName"`;
    }
  } else {
      `zenity --info --text="$file could not be opened"`;
  }
}

