#!/usr/bin/perl -w

my $height = `zenity  --list  --text "Select long edge size:" --radiolist  --column " " --column "Height" FALSE 320 FALSE 640 TRUE 800 FALSE 1024 FALSE 1200 FALSE 1500 FALSE 1800`;
my $dpi = `zenity --scale --text "Select DPI" --min-value=72 --max-value=300 --value=72 --step 2`;
my $quality = `zenity --scale --text "Select Quality" --min-value=20 --max-value=100 --value=90 --step 2`;
my $overwrite = `zenity --title "Adjust In Place?" --question --text  "Adjust in place (Yes) or create new file (No)?"; echo \$?`;
chomp($height);
chomp($dpi);
chomp($quality);
chomp($overwrite);

my $paths = $ENV{NAUTILUS_SCRIPT_SELECTED_FILE_PATHS};
if ((!$paths) || ($paths eq "")) {
  $paths = $ENV{NEMO_SCRIPT_SELECTED_FILE_PATHS};
}

my @files = split("\n", $paths);
my $filecount = @files;
if ($filecount > 0) {
  my @cmd = ();
  push (@cmd, $ENV{"HOME"}.'/.local/bin/webify.pl');
  push (@cmd, '-height', $height);
  push (@cmd, '-quality', $quality);
  push (@cmd, '-dpi', $dpi);
  push (@cmd, '-overwrite') if ($overwrite == 0);
  foreach my $file (@files) {
    if (-e $file) {
      push (@cmd, "'".$file."'");
    }
  }
  my $command = join(' ', @cmd);
  `bash -c "($command) 2>&1 | zenity --progress --pulsate --auto-close --auto-kill"`;
}

