#!/usr/bin/perl -w

use strict;

my $paths = $ENV{NAUTILUS_SCRIPT_SELECTED_FILE_PATHS};
if ((!$paths) || ($paths eq "")) {
  $paths = $ENV{NEMO_SCRIPT_SELECTED_FILE_PATHS};
}

my @files = split("\n", $paths);
foreach my $file (@files)
{
  if ( -e $file )
  {
    `festival --tts '$file'`;
  }
}

