#!/usr/bin/perl -w

my $paths = $ENV{NAUTILUS_SCRIPT_SELECTED_FILE_PATHS};
if ((!$paths) || ($paths eq "")) {
  $paths = $ENV{NEMO_SCRIPT_SELECTED_FILE_PATHS};
}

my @files = split("\n", $paths);
my $filecount = @files;
if ($filecount > 0) {
  my @cmd = ();
  push (@cmd, '/usr/bin/shred');
  push (@cmd, '-n1');
  push (@cmd, '-u');
  foreach my $file (@files) {
    if (-e $file) {
      push (@cmd, "'".$file."'");
    }
  }
  my $command = join(' ', @cmd);
  `bash -c "($command) 2>&1 | zenity --progress --pulsate --auto-close --auto-kill"`;
}

