# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "windows/10pron"
  config.vm.guest = :windows
  config.vm.communicator = "winrm"

  # windows installs updates during startup and shutdown
  # larger timeouts hopefully prevents bricking the vm
  config.vm.boot_timeout = 600
  config.vm.graceful_halt_timeout = 600

  # port forward WinRM and RDP
  config.vm.network :forwarded_port, guest: 3389, host: 3389
  config.vm.network :forwarded_port, guest: 5985, host: 5985, id: "winrm", auto_correct: true

  config.winrm.username = "vagrant"
  config.winrm.password = "vagrant"

  config.vm.provider "virtualbox" do |vb|
    # vb.gui = true
    vb.memory = "8192"
    vb.cpus = 4
    vb.name = "WindowsVagrant"
  end

end

