# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "macos/highsierra"
  config.vm.guest = :freebsd
  config.vm.communicator = "ssh"

  # nfs doesn't currently work either
  # config.vm.network "private_network", type: "dhcp"
  # config.vm.synced_folder "../../shared_files", "/User/vagrant/vagrant_shared", type: "nfs", :disabled => true

  # regular synced folder are not supported under Mac OS X
  config.vm.synced_folder ".", "/vagrant", :disabled => true


  config.ssh.username = "vagrant"
  config.ssh.password = "vagrant"
  config.ssh.insert_key = true

  config.vm.provider "virtualbox" do |vb|
    # vb.gui = true
    vb.memory = "16384"
    vb.cpus = 6

    vb.customize ["modifyvm", :id, "--cpuidset", "00000001","000106e5","00100800","0098e3fd","bfebfbff"]
    vb.customize ["setextradata", :id, "VBoxInternal/Devices/efi/0/Config/DmiSystemProduct", "iMac11,3"]
    vb.customize ["setextradata", :id, "VBoxInternal/Devices/efi/0/Config/DmiSystemVersion", "1.0"]
    vb.customize ["setextradata", :id, "VBoxInternal/Devices/efi/0/Config/DmiBoardProduct", "Iloveapple"]
    vb.customize ["setextradata", :id, "VBoxInternal/Devices/smc/0/Config/DeviceKey", "ourhardworkbythesewordsguardedpleasedontsteal(c)AppleComputerInc"]
    vb.customize ["setextradata", :id, "VBoxInternal/Devices/smc/0/Config/GetKeyFromRealSMC", "1"]
    vb.customize ["setextradata", :id, "VBoxInternal2/EfiGraphicsResolution", "1440x900"]
  end

end
